Repository aqualinkorg/aqualink-app, pull requests merged in 2020-06, with the labels that each got.

#19 Add circle-ci config
  .circleci/config.yml
  api/src/reefs/reefs.controller.spec.ts
  website/package.json
Labels: devops

#14 Add utility function to calculate degree heating days
  packages/api/package.json
  packages/api/src/utils/temperature.test.ts
  packages/api/src/utils/temperature.ts
Labels: api, backend

#31 Simplify App Engine deployment and add a staging service
  README.md
  package.json
  packages/api/app-staging.yaml
  packages/api/ormconfig.ts
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/tsconfig.build.json
  yarn.lock
Labels: devops

#41 🎨 Update the form mobile version
  packages/application/src/Form/index.tsx
Labels: bug, frontend, skills:React, skills:Typescript
